import type {
  User, Opportunity, Claim, Benefits, PointsSummary,
  RedemptionOption, PointsTransaction,
} from '@/types';

// ─── Mock User ────────────────────────────────────────────────────────────────
export const MOCK_USER: User = {
  id: 'usr_001',
  firstName: 'Alex',
  lastName: 'Rivera',
  email: 'alex.rivera@email.com',
  memberId: 'CR-2024-88421',
  planName: 'Premier Health PPO',
  groupNumber: 'GRP-4421',
  tier: 'silver',
  avatarInitials: 'AR',
};

// ─── Mock Points ─────────────────────────────────────────────────────────────
export const MOCK_TRANSACTIONS: PointsTransaction[] = [
  { id: 't1', description: 'Switched to generic Atorvastatin', points: 500, type: 'earned', date: '2025-05-28', category: 'medication' },
  { id: 't2', description: 'Annual Physical completed', points: 300, type: 'earned', date: '2025-05-15', category: 'preventive' },
  { id: 't3', description: 'Enrolled in mail-order pharmacy', points: 500, type: 'earned', date: '2025-05-10', category: 'mail_delivery' },
  { id: 't4', description: 'Specialist visit survey', points: 50,  type: 'earned', date: '2025-05-05', category: 'survey' },
  { id: 't5', description: 'Redeemed for copay credit', points: -1000, type: 'redeemed', date: '2025-04-30', category: 'redemption' },
  { id: 't6', description: 'Flu shot vaccination', points: 300, type: 'earned', date: '2025-04-22', category: 'preventive' },
  { id: 't7', description: 'Completed health assessment', points: 200, type: 'earned', date: '2025-04-10', category: 'bonus' },
  { id: 't8', description: 'Uploaded upcoming care plan', points: 50, type: 'earned', date: '2025-04-02', category: 'upcoming_care' },
  { id: 't9', description: 'Monthly engagement bonus', points: 100, type: 'earned', date: '2025-03-31', category: 'bonus' },
  { id: 't10', description: 'Redeemed for premium reduction', points: -500, type: 'redeemed', date: '2025-03-15', category: 'redemption' },
];

export const MOCK_POINTS: PointsSummary = {
  balance: 2350,
  earnedThisYear: 4850,
  redeemedThisYear: 1500,
  savingsThisYear: 287,
  transactions: MOCK_TRANSACTIONS,
};

// ─── Mock Opportunities ───────────────────────────────────────────────────────
export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp_001',
    type: 'medication',
    title: 'Switch to Generic Metformin',
    shortDescription: 'Save up to $45/month by switching from Glucophage to generic Metformin.',
    fullDescription: 'Your current prescription for Glucophage (brand-name metformin) has a lower-cost generic equivalent that is clinically identical. Switching saves you money on every refill with no difference in effectiveness.',
    pointsReward: 500,
    estimatedSavings: 45,
    status: 'available',
    dueDate: '2025-07-01',
    steps: [
      'Review the cost comparison below',
      'Generate a doctor note to request the switch',
      'Take the note to your next appointment or send it via patient portal',
      'Pick up your first generic refill to earn points',
    ],
    icon: 'pill',
    category: 'Medication Savings',
  },
  {
    id: 'opp_002',
    type: 'preventive',
    title: 'Schedule Your Mammogram',
    shortDescription: 'Annual mammogram is 100% covered and overdue by 3 months.',
    fullDescription: 'Preventive mammograms are covered at 100% with no cost to you under your Premier Health PPO plan. Your last recorded mammogram was over 14 months ago. Scheduling one this month earns you points and keeps you on track.',
    pointsReward: 300,
    estimatedSavings: 180,
    status: 'available',
    dueDate: '2025-06-30',
    steps: [
      'Call your OB-GYN or a participating imaging centre',
      'Schedule within an in-network facility',
      'Attend your appointment',
      'Your claim data will update within 2 weeks and points will be credited',
    ],
    icon: 'heart-pulse',
    category: 'Preventive Care',
  },
  {
    id: 'opp_003',
    type: 'mail_delivery',
    title: 'Set Up Mail-Order Pharmacy',
    shortDescription: 'Get a 90-day supply of your maintenance meds for the price of a 60-day supply.',
    fullDescription: 'You have three maintenance medications currently filled at retail. Switching these to mail-order pharmacy gives you a 90-day supply for the copay of a 60-day supply — and earns you a one-time points bonus for each drug transferred.',
    pointsReward: 500,
    estimatedSavings: 120,
    status: 'in_progress',
    steps: [
      'Log in to the mail-order pharmacy portal (link provided)',
      'Transfer your three eligible prescriptions',
      'Confirm your home delivery address',
      'Receive your first 90-day shipment to earn points',
    ],
    icon: 'truck-delivery',
    category: 'Mail Delivery',
  },
  {
    id: 'opp_004',
    type: 'preventive',
    title: 'Annual Dental Exam',
    shortDescription: '2 preventive dental visits per year are covered — you have 1 remaining.',
    fullDescription: 'Your dental plan covers two preventive exams and cleanings per calendar year at 100%. You have used one visit this year. Scheduling your second visit now prevents the benefit from expiring.',
    pointsReward: 200,
    estimatedSavings: 95,
    status: 'available',
    steps: [
      'Find an in-network dentist using the provider search',
      'Schedule a routine exam and cleaning',
      'Attend your appointment before December 31',
    ],
    icon: 'tooth',
    category: 'Preventive Care',
  },
  {
    id: 'opp_005',
    type: 'specialist',
    title: 'Complete Your Cardiology Follow-up Survey',
    shortDescription: 'Help improve care quality — take a 2-minute survey after your recent cardiologist visit.',
    fullDescription: 'You recently visited Dr. Okafor (Cardiology) on May 12. Your feedback helps your health plan and the provider improve care coordination. Takes under 2 minutes.',
    pointsReward: 50,
    estimatedSavings: 0,
    status: 'available',
    steps: [
      'Tap "Start Survey" below',
      'Answer 5 quick questions about your visit',
      'Submit — points are credited instantly',
    ],
    icon: 'clipboard-text',
    category: 'Surveys',
  },
  {
    id: 'opp_006',
    type: 'medication',
    title: 'Switch to Generic Lisinopril',
    shortDescription: 'Generic Lisinopril is bioequivalent to Zestril — save $38/month.',
    fullDescription: 'Your plan\'s formulary places brand-name Zestril on Tier 3 at a $55 copay. Generic Lisinopril is on Tier 1 at $17. Clinically identical, FDA-approved, and costs you $38 less every month.',
    pointsReward: 500,
    estimatedSavings: 38,
    status: 'completed',
    steps: [
      'Review the formulary comparison',
      'Generate and send doctor note',
      'Switch at next refill',
    ],
    icon: 'pill',
    category: 'Medication Savings',
  },
  {
    id: 'opp_007',
    type: 'upcoming_care',
    title: 'Log Your Upcoming MRI',
    shortDescription: 'Your plan may have a lower-cost imaging centre option nearby.',
    fullDescription: 'You have an MRI scheduled next month. Different in-network facilities can vary by hundreds of dollars in cost-sharing for the same procedure. Log your upcoming visit so we can surface the best value options near you.',
    pointsReward: 50,
    estimatedSavings: 0,
    status: 'available',
    steps: [
      'Tap "Log Upcoming Care" below',
      'Enter the procedure type and planned date',
      'We\'ll analyse your options and notify you of savings opportunities',
    ],
    icon: 'calendar-check',
    category: 'Upcoming Care',
  },
];

// ─── Mock Claims ──────────────────────────────────────────────────────────────
export const MOCK_CLAIMS: Claim[] = [
  {
    id: 'clm_001',
    claimNumber: 'CLM-2025-10041',
    date: '2025-05-28',
    serviceDate: '2025-05-22',
    providerName: 'Northside Family Medicine',
    providerType: 'Primary Care',
    serviceDescription: 'Office visit — established patient',
    billedAmount: 250,
    planAllowed: 180,
    insurancePaid: 144,
    patientResponsibility: 36,
    deductibleApplied: 0,
    copayApplied: 30,
    coinsuranceApplied: 6,
    status: 'processed',
    diagnosisCodes: ['Z00.00'],
  },
  {
    id: 'clm_002',
    claimNumber: 'CLM-2025-09887',
    date: '2025-05-15',
    serviceDate: '2025-05-12',
    providerName: 'Dr. Emmanuel Okafor, MD',
    providerType: 'Cardiology',
    serviceDescription: 'Specialist consultation — new patient',
    billedAmount: 420,
    planAllowed: 310,
    insurancePaid: 248,
    patientResponsibility: 62,
    deductibleApplied: 0,
    copayApplied: 60,
    coinsuranceApplied: 2,
    status: 'processed',
  },
  {
    id: 'clm_003',
    claimNumber: 'CLM-2025-09512',
    date: '2025-05-05',
    serviceDate: '2025-05-01',
    providerName: 'City Lab & Diagnostics',
    providerType: 'Laboratory',
    serviceDescription: 'Comprehensive metabolic panel + lipid panel',
    billedAmount: 185,
    planAllowed: 95,
    insurancePaid: 95,
    patientResponsibility: 0,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    status: 'processed',
    diagnosisCodes: ['Z00.00', 'E11.9'],
  },
  {
    id: 'clm_004',
    claimNumber: 'CLM-2025-09201',
    date: '2025-04-28',
    serviceDate: '2025-04-25',
    providerName: 'QuickCare Urgent Care',
    providerType: 'Urgent Care',
    serviceDescription: 'Urgent care visit — acute illness',
    billedAmount: 310,
    planAllowed: 220,
    insurancePaid: 170,
    patientResponsibility: 50,
    deductibleApplied: 0,
    copayApplied: 50,
    coinsuranceApplied: 0,
    status: 'processed',
  },
  {
    id: 'clm_005',
    claimNumber: 'CLM-2025-08944',
    date: '2025-04-18',
    serviceDate: '2025-04-17',
    providerName: 'Greenwood Pharmacy',
    providerType: 'Pharmacy',
    serviceDescription: 'Atorvastatin 20mg — 30-day supply',
    billedAmount: 22,
    planAllowed: 22,
    insurancePaid: 5,
    patientResponsibility: 17,
    deductibleApplied: 0,
    copayApplied: 17,
    coinsuranceApplied: 0,
    status: 'processed',
  },
  {
    id: 'clm_006',
    claimNumber: 'CLM-2025-08733',
    date: '2025-04-08',
    serviceDate: '2025-04-05',
    providerName: 'Advanced Imaging Partners',
    providerType: 'Radiology',
    serviceDescription: 'X-Ray — chest, 2 views',
    billedAmount: 290,
    planAllowed: 210,
    insurancePaid: 0,
    patientResponsibility: 210,
    deductibleApplied: 210,
    copayApplied: 0,
    coinsuranceApplied: 0,
    status: 'pending',
  },
  {
    id: 'clm_007',
    claimNumber: 'CLM-2025-07901',
    date: '2025-03-21',
    serviceDate: '2025-03-19',
    providerName: 'Northside Family Medicine',
    providerType: 'Primary Care',
    serviceDescription: 'Annual wellness visit — preventive',
    billedAmount: 375,
    planAllowed: 280,
    insurancePaid: 280,
    patientResponsibility: 0,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    status: 'processed',
    diagnosisCodes: ['Z00.00'],
  },
];

// ─── Mock Benefits ────────────────────────────────────────────────────────────
export const MOCK_BENEFITS: Benefits = {
  planYear: '2025',
  inNetworkOnly: false,
  deductible: {
    individual: { met: 415, total: 1500 },
    family:     { met: 890, total: 3000 },
  },
  outOfPocket: {
    individual: { met: 415, total: 5000 },
    family:     { met: 890, total: 10000 },
  },
  copayTiers: [
    { tier: 1, label: 'Tier 1 — Generic',       description: 'Generic prescriptions',             copay: 10,  examples: ['Metformin', 'Lisinopril', 'Atorvastatin'] },
    { tier: 2, label: 'Tier 2 — Preferred Brand', description: 'Preferred brand-name medications', copay: 35,  examples: ['Januvia', 'Farxiga', 'Eliquis'] },
    { tier: 3, label: 'Tier 3 — Non-Preferred',  description: 'Non-preferred brand medications',  copay: 70,  examples: ['Glucophage', 'Zestril', 'Crestor'] },
    { tier: 4, label: 'Tier 4 — Specialty',      description: 'Specialty/biologic medications',   copay: 150, examples: ['Humira', 'Ozempic', 'Keytruda'] },
  ],
  preventiveServices: [
    { id: 'prev_1', name: 'Annual Physical',           frequency: 'Once per year',    covered: true,  lastCompleted: '2025-03-19', nextDue: '2026-03-19' },
    { id: 'prev_2', name: 'Mammogram (women 40+)',     frequency: 'Once per year',    covered: true,  lastCompleted: '2024-04-10', nextDue: '2025-04-10' },
    { id: 'prev_3', name: 'Flu Vaccine',               frequency: 'Once per season',  covered: true,  lastCompleted: '2024-10-05', nextDue: '2025-10-01' },
    { id: 'prev_4', name: 'Colorectal Cancer Screening', frequency: 'Every 10 years', covered: true },
    { id: 'prev_5', name: 'Blood Pressure Screening',  frequency: 'Every 2 years',    covered: true,  lastCompleted: '2025-03-19' },
    { id: 'prev_6', name: 'Cholesterol Screening',     frequency: 'Every 5 years',    covered: true,  lastCompleted: '2025-04-17', nextDue: '2030-04-17' },
    { id: 'prev_7', name: 'Diabetes Screening',        frequency: 'Every 3 years',    covered: true,  lastCompleted: '2025-04-17' },
    { id: 'prev_8', name: 'Eye Exam',                  frequency: 'Once per year',    covered: true },
  ],
};

// ─── Redemption Options ───────────────────────────────────────────────────────
export const REDEMPTION_OPTIONS: RedemptionOption[] = [
  { id: 'red_1', type: 'premium_reduction',  label: 'Premium Reduction',  description: 'Reduce your next monthly premium payment', minPoints: 500,  conversionRate: 100, icon: 'receipt-percent' },
  { id: 'red_2', type: 'copay_credit',        label: 'Copay Credit',       description: 'Apply as credit against your next copay',   minPoints: 300,  conversionRate: 100, icon: 'credit-card-check' },
  { id: 'red_3', type: 'deductible_credit',   label: 'Deductible Credit',  description: 'Applied directly to your annual deductible', minPoints: 1000, conversionRate: 100, icon: 'piggy-bank' },
  { id: 'red_4', type: 'gift_card',           label: 'Gift Card',          description: 'Redeem for a digital gift card',            minPoints: 1000, conversionRate: 100, icon: 'gift' },
  { id: 'red_5', type: 'hsa_contribution',    label: 'HSA Contribution',   description: 'Contributed to your Health Savings Account', minPoints: 500,  conversionRate: 100, icon: 'heart-circle' },
];
